### ISSUE TITLE
`npm run build` infinite echo loop

### ISSUE THREAD

**Issue by rsmets** [centrehq/verite#383]
Upon trying to setup the demos with `npm run setup` from the tip of main [0efdfaf] the install gets into an infinite echo loop. It seems like it is thanks to the npm script `build`.

![image](https://user-images.githubusercontent.com/2586247/159824927-ac876f07-d89c-4deb-b127-a558d81082a8.png)

**Comment by kimdhamilton** [comment]
Interesting, i just tried this out on a clean repo and couldn't repro. Could it be environment/node version-specific? 

Has anyone else run into this? If so, please add details to help get to the bottom of this.

**Comment by rsmets** [comment]
Ahh oops... skipped right over the npmv7 requirement! Just tried it on a machine with v7 and it work as expected. 

Thanks for the quick response. Closing.
