### ISSUE TITLE
Minor Fix: Purge dependency on schemata from wallet

### ISSUE THREAD

**Issue by euj1n0ng** [centrehq/verite#470]
Verite wallet has only one part - [`CredentialDetail` component](https://github.com/centrehq/verite/blob/6279df01df3b58574987f3f393d811a2352c1c2d/packages/wallet/src/components/CredentialDetail.tsx#L31) that depends on specific credential types (attestation schemas). Attestation properties are extracted according to the schema for display purpose.

Actually, it is unnecessary and redundant.
The properties are also extracted by a manifest utility function - [`getDisplayProperties`](https://github.com/centrehq/verite/blob/6279df01df3b58574987f3f393d811a2352c1c2d/packages/wallet/src/components/CredentialDetail.tsx#L125) in a schema-agnostic way.
And since PR #458 (this is a super superb update, congrats 🎉) allowed user-defined types of credentials, I recommend removing the dependency on schemata.

**Comment by kimdhamilton** [comment]
Thanks @euj1n0ng !
