### ISSUE TITLE
Scanning the qr code on the terminal screen with the expo go app, I get a network connection timed out error

### ISSUE THREAD

**Issue by JayAdityaNautiyal** [centrehq/verite#472]
Hi team,
I cloned the github repo https://github.com/centrehq/verite
and followed the instructions as given in the readme file.
It says it is required to use NodeJS14 and npm7 but Node14 comes with a default combination with npm6 and I can't use npm7 with Node14. I have also used higher versions of Node i.e above 14 in combination with npm7 and above. That also didn't work.
I'll be highly obliged if you suggest anything to me anything, so that I can run the sample.
I've attached the error screenshot too
Thanks.
![image](https://user-images.githubusercontent.com/80779224/192781827-9e8e37ee-a5ab-4a34-89fb-6615dbcd35eb.png)

**Comment by polluterofminds** [comment]
@JayAdityaNautiyal I just did a fresh clone on a macbook with the following versions of node and npm: 

Node: 16.17.0
NPM: 8.15.0

When I run `npm run setup` everything works fine. 

Can you share the specific node version and npm version by checking `node -v` and `npm -v`?

**Comment by JayAdityaNautiyal** [comment]
Thanks @polluterofminds 
Verite should update its documentation for the pre-requisites section and update the node and npm versions. Though I still had issues running it on windows.

So I spinned a linux machine on Azure and installed node and npm with versions used by you, and the command  **npm run setup** is running fine. 

But when I run the **npm run wallet** and scan the code on screen on the expo go app, I get a network connection timed out on the expo go app for which I have attached a screenshot.
Can you please help with it?

![WhatsApp Image 2022-09-30 at 1 38 21 PM](https://user-images.githubusercontent.com/80779224/193223275-bacb09be-1e6e-4e8e-8de6-22a353a2f7cc.jpeg)

**Comment by JayAdityaNautiyal** [comment]
anyone there ?
@polluterofminds 
@kimdhamilton

**Comment by polluterofminds** [comment]
I'm looking into this now. Because you're running on a VM, I wonder if you're hitting some firewall issues. Expo requires tunneling to run locally. Will try to replicate.

**Comment by JayAdityaNautiyal** [comment]
thanks @polluterofminds 
I thought it was an issue with the cloud so I used local VirtualBox and started a linux machine out of it. I am getting the same error as above on the expo go app.
Maybe this issue is with the VM.
I don't have a Mac OS, can you please look into it so that how can I run the sample.
Thanks.

**Comment by polluterofminds** [comment]
Yeah let's try to get this working on your windows machine @JayAdityaNautiyal! 

You said: 

> Verite should update its documentation for the pre-requisites section and update the node and npm versions. Though I still had issues running it on windows. 

What exactly were those issues on Windows? Can you share as many details as possible including the errors?

**Comment by JayAdityaNautiyal** [comment]
sure @polluterofminds 
So the issue on running the sample on my windows machine locally was that when I was running the command "npm run setup" , I would get an error that " '.' is not recognized as an internal or external command,
operable program or batch file." I've attached it below:
![image](https://user-images.githubusercontent.com/80779224/194469993-756ba4e4-8d1f-40c8-a689-668394544585.png)
Then I tried to run the commands in the ./bin/setup file, like npm install. That also threw error as :
![image](https://user-images.githubusercontent.com/80779224/194470142-5ff42697-318a-46b6-a438-d648b466fb24.png)

Running it on a VM using virtual box or AZURE cloud, I could run the application and get the qr code on screen but while scanning it from the mobile app it would give "connection timed out error".
So we tried it on mac and the URL for "**metro waiting on exp://***  " was different in mac(where it is running correctly). So can you also tell where in the code can we enhance these port configurations set the environment variables as I couldn't find where are the ports(like 19000) have been configured. The connection with the URL exp://10.1.0.4:19000 was not done so we can see a way of changing the configuration, and running the code on VM as well.

**Comment by polluterofminds** [comment]
Looks like we might need to conditionally update the setup script for Windows. I was under the impression that we had Windows users successfully running this, but maybe not. 

This thread indicates that the relative path format of the setup script is throwing things off. If you want to confirm this, you could manually go into the `package.json` and try updating `./bin/setup` to the absolute path of that file on your machine. 

https://stackoverflow.com/questions/48321639/error-is-not-recognized-as-an-internal-or-external-command-operable-program-o

**Comment by euj1n0ng** [comment]
Verite is set up as an [npm workspace](https://docs.npmjs.com/cli/v7/using-npm/workspaces) (which requires npm v7 or greater). The dependencies for all packages are installed unifiedly from the root level using `npm install`. As long as Node.js v14 is LTS, you can use it by upgrading the npm version to 7. (`npm i -g npm@7`)

Verite's CLI scripts were written in UNIX style (e.g. inline mutli-commands delimited by `;` which cannot be parsed in Windows, besides finding the path of a bash script file).
In order to setup the dev environment on Windows, you have to change the UNIX style scripts into Windows style in all `package.json` files. It sounds a little tricky.

Alternatively, on a Windows machine, we can use [WSL](https://learn.microsoft.com/en-us/windows/wsl/) without changing UNIX style scripts at all. I think this is the best option.

Regarding the timedout issue in lauching wallet, tunneling application is required in Expo as long as your device isn't connected to your LAN. Once npm packages are installed, you can directly run the wallet by executing `npx expo start --tunnel` in the wallet folder. (In Expo SDK v45, the UI of tunneling isn't supported anymore, but only available via CLI.)

After all, the current Verite documentation is very correct and has no issue at all.

PS. To avoid the hassles due to npm workspace dependency management, you can extract the wallet as an indenpendent repo like [this](https://github.com/euj1n0ng/demo-identity-wallet). Though I didn't make it up-to-date, it is cross-platform workable at least.

**Comment by JayAdityaNautiyal** [comment]
Hi @euj1n0ng 
I tried using WSL on windows and I was able to run the command **npm run setup** and **npm run dev**.
But when I run **npm run wallet** and scan the qr code on the screen using the mobile app, I get the same **network response timed out ** error.
The output of **npm run wallet** as received in the console is :
![image](https://user-images.githubusercontent.com/80779224/194721788-ce53ca8d-8309-4ed5-8c19-952aa1f1e92f.png)

And the error on the mobile screen is :
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/80779224/194721890-9b5b9182-41e8-460e-bf37-9fe09b3109eb.png)
![Screenshot_2022-10-09-00-08-36-32_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/80779224/194722622-bc7e4851-1669-4d07-9511-e76ccb87df55.jpg)

I also extracted the wallet from the independent repo shared by @euj1n0ng and received the same error as above  on the mobile application while scanning the qr code.

If you can please fix this from here, it will be a great help.

**Comment by JayAdityaNautiyal** [comment]
Hi @euj1n0ng @polluterofminds @kimdhamilton 
Can you  please look into it as few of my folks tried on their windows machine as well and all had same errors!

**Comment by kimdhamilton** [comment]
Hi @JayAdityaNautiyal, in general we're not staffed to help with platform-specific support, but have you tried looking at guidance for similar projects? I.e., I imagine it might be common with other react projects on windows. 

We're really glad you're using this project, and we'll leave this issue open in case another windows user can help

**Comment by euj1n0ng** [comment]
@JayAdityaNautiyal , share your `challengeTokenUrl`.
I am sure you're troubling with the same issue - tunneling. But, this time, not on the mobile wallet app but on the demo web app.

**Comment by sumitesh9** [comment]
I have also followed the same steps (tunneling + WSL), and I am hereby sharing the challengeTokenUrl. Does anyone have an idea how to fix the issue?
![image](https://user-images.githubusercontent.com/30365680/203484412-eb547355-4651-4567-9c3c-a715d2d1f717.png)

**Comment by kimdhamilton** [comment]
I still can't repro
