### ISSUE TITLE
Improve credential mapping in wallet in a global context

### ISSUE THREAD

**Issue by euj1n0ng** [centrehq/verite#474]
Verite wallet currently assumes manifest input/output descriptor IDs have a 1:1 mapping to Verifiable Credential types. As there is no guarantee that every Verite SDK users will always assign globally unique input/output descriptor IDs, it should be improved. According to [DIF standard](https://identity.foundation/credential-manifest/#output-descriptor-object), `id` property just needs to be a string that does not conflict with the `id` of another output descriptor in the same manifest.

I suggest to use `schema` property of output descriptor in the format of **URI**. And will register only output descriptor as the VC type instead of entire manifest which could include more than one output descriptors. This schema registry supports classification of VCs for the purpose of display and exchange in wallet.

Let me know your feedback. @kimdhamilton  If you agree, I will make a PR accordingly.

**Comment by kimdhamilton** [comment]
+1, I like this approach. Thanks @euj1n0ng !

**Comment by kimdhamilton** [comment]
Fixed by @euj1n0ng in commit #505
